; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; --- GESTION DES BIBLIOTHÈQUES STANDARDS ---
lib_deps =
    mikalhart/TinyGPSPlus @ ^1.0.3
    esphome/AsyncTCP-esphome @ ^2.1.4
    esphome/ESPAsyncWebServer-esphome @ ^3.2.2

; --- SÉCURITÉ COMPILATION ---
; Permet d'éviter les alertes strictes sur certaines anciennes syntaxes de chaînes HTML
build_flags = -Wno-write-strings
board_build.filesystem = littlefs